name: scratcher
description: Scratch card widget which temporarily hides content from the user.
homepage: https://github.com/vintage/scratcher

version: 2.4.0

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: null
